#!/bin/bash -e

go get github.com/vito/gosub

if [ ! $(which gosub) ]; then
  echo "Gosub required to update dependencies in bosh/*/spec files."
  echo 'Please install with `go get github.com/vito/gosub`'
  exit 1
fi

pushd $(dirname $0)/..
  function sync_package() {
    bosh_pkg=${1}
    shift

    (
      set -e

      cd packages/${bosh_pkg}

      {
        cat spec | grep -v '# gosub'

        for package in $(gosub list "$@"); do
          repo=$(echo ${2} | cut -f1-3 -d/)
          echo ${package} | sed -e 's/\(.*\)/  - \1\/*.go # gosub/g'
        done
      } > spec.new

      mv spec.new spec
    )
  }

  sync_package service-metrics     -app code.cloudfoundry.org/service-metrics

  wait
popd
