#!/bin/bash

ssh -o StrictHostKeyChecking=no -o "UserKnownHostsFile /dev/null" -T git@github.com > /dev/null 2>&1

if [ $? -ne 1 ]; then
  echo "Unable to connect to github.com over SSH. You may need to add a valid SSH key to your ~/.ssh/ folder or using ssh-add"
  exit 1
fi

set -xe

git submodule update --init --recursive
bundle install
